### ISSUE TITLE
Bitcode not working for Archive

### ISSUE THREAD

**Issue by mlchild** [Iterable/swift-sdk#73] opened 2019-04-05 01:26 UTC
Issue archiving with bitcode (for both main framework and extensions):

ld: bitcode bundle could not be generated because '...../Frameworks/IterableAppExtensions.framework/IterableAppExtensions' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '...../Frameworks/IterableAppExtensions.framework/IterableAppExtensions' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by tapashmajumder** [comment] 2019-04-05 01:40
Can you please list steps to repro this issue?

**Comment by mlchild** [comment] 2019-04-05 01:43
Download frameworks from "releases" page on github
Drag frameworks into xcode (as instructed, embedded binaries etc)
Build in development mode, everything works fine
Archive for iOS app store distributions (with Bitcode enabled)
See above error

**Comment by tapashmajumder** [comment] 2019-04-05 01:50
Thanks. We will take a look at this issue. In the meantime would you be able to try Cocoapods or Carthage?

**Comment by mlchild** [comment] 2019-04-05 01:52
Yeah, will try Carthage

**Comment by tapashmajumder** [comment] 2019-04-05 19:18
I have attached different files to the release. Can you please check if this solves the problem?

**Comment by tapashmajumder** [comment] 2019-04-23 22:33
I have attached new binary files to the `6.0.8` version release and I have validated that archiving is working using these binaries. I am closing this issue. Please reopen if the issue is not resolved for you.

**Closed by tapashmajumder** 2019-04-23 22:33 UTC
