### ISSUE TITLE
Manual integration not working

### ISSUE THREAD

**Issue by PSBT** [Iterable/swift-sdk#84] opened 2019-04-30 22:04 UTC
I've followed the manual installation instructions https://github.com/Iterable/swift-sdk#manual-installation).

The project compiles but when trying to run it in the simulator I get:
```
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Users/pedro/Library/Developer/CoreSimulator/Devices/B1720EDD-39FC-44D2-BDD7-61B2E9DE83F1/data/Containers/Bundle/Application/DA302F26-73DA-46D6-810E-C29E92AE862F/Chess.app/Frameworks/IterableSDK.framework/IterableSDK
  Reason: no suitable image found.  Did find:
	/usr/lib/swift/libswiftCore.dylib: mach-o, but not built for iOS simulator
```
The instructions only state two things:

1. Add framework to "embedded binaries" section.
2. Set "Always Embed Swift Standard Libraries" to Yes

What am I missing? I tested with the framework found in IterableSDK.zip v6.0.8.

**Comment by tapashmajumder** [comment] 2019-04-30 22:15
This could be related to an MacOS/Xcode issue that some other users are having. 

Can you please upgrade to latest MacOS and Xcode 10.2? Also if possible can you please attach a sample project with problem.

**Comment by PSBT** [comment] 2019-04-30 23:10
Yes this no longer occurs in Xcode Version 10.2.1 (10E1001). Thanks!

**Comment by PSBT** [comment] 2019-05-01 21:12
I'm still having issues. As I previously said, the project now compiles with the manual installation and Xcode version 10.2.1. I can even import the framework successfully:

`@import IterableSDK;`

But when I try to initialize the SDK with:
```
IterableConfig *config = [[IterableConfig alloc] init];
config.pushIntegrationName = @"<your-iterable-push-integration-name>";
[IterableAPI initializeWithApiKey:@"<your-api-key>" launchOptions:launchOptions config:config]
```
Xcode tells me:
> Use of undeclared identifier 'IterableConfig'

What am I missing?

**Comment by PSBT** [comment] 2019-05-01 21:36
Here you can find a single view Xcode project in which I integrated the SDK v6.0.8 manually and that shows the error mentioned above: https://www.dropbox.com/s/yizfigxh2vfy3v3/IterableTest_ManualInstallation.zip?dl=0

**Comment by tapashmajumder** [comment] 2019-05-01 21:37
@PSBT You may have helped me repro an issue that others were having :-). It appears that after Xcode 10.2 upgrade, objc projects are having the problem that you are having. I am looking into this.
[related-issue](https://github.com/Iterable/swift-sdk/issues/79l)

This problem seems to be restricted to objc code when using simulators. In the meantime can you please confirm that. your code will compile when using 'Generic iOS Device' or an actual 'iPhone'?

**Comment by PSBT** [comment] 2019-05-01 21:40
If I don't add:
```
IterableConfig *config = [[IterableConfig alloc] init];
config.pushIntegrationName = @"<your-iterable-push-integration-name>";
[IterableAPI initializeWithApiKey:@"<your-api-key>" launchOptions:launchOptions config:config]
```

Then it compiles in both simulators and device. If I add the code above then it doesn't compile anywhere.

**Comment by tapashmajumder** [comment] 2019-05-01 21:45
@PSBT Thank you so much. I have reproduced this issue and I am working on it as mentioned in my previous comment. In the meantime, can you please compile using **real device** and not simulator. That will compile and get you going while I work in the fix.

**Comment by tapashmajumder** [comment] 2019-05-01 21:46
Hmm.. it it is compiling on real device for me.

**Comment by PSBT** [comment] 2019-05-01 22:03
Sorry! It's also compiling for device for me!

**Comment by tapashmajumder** [comment] 2019-05-01 22:04
Great. You have helped me repro an issue. I will keep working on the fix while you work on real device in the meantime.

**Comment by PSBT** [comment] 2019-05-01 22:05
Great!

**Comment by tapashmajumder** [comment] 2019-05-01 23:05
Can you please try this zip file?
[IterableSDK.zip](https://github.com/Iterable/swift-sdk/files/3136262/IterableSDK.zip)

**Comment by PSBT** [comment] 2019-05-01 23:18
Yes. Now it compiles in the simulators!

**Comment by PSBT** [comment] 2019-05-02 15:31
When can we expect an official release with this fix? Thanks!

**Comment by tapashmajumder** [comment] 2019-05-02 18:11
@PSBT I have added the correct zip files to the release. I have also updated our zip generation scripts.

I am closing this issue. Please reopen if the latest zip does not solve this problem for you. Thanks!

**Closed by tapashmajumder** 2019-05-02 18:11 UTC

**Comment by PSBT** [comment] 2019-05-03 01:05
Sorry I don't see a new release in https://github.com/Iterable/swift-sdk/releases.

**Comment by tapashmajumder** [comment] 2019-05-03 01:24
It is the same release 6.0.8 [here](https://github.com/Iterable/swift-sdk/releases/tag/6.0.8).

I have just updated the zip files there since there is no code change.

**Comment by PSBT** [comment] 2019-05-03 17:03
I see! Tested the zip form 6.0.8 and it compiles both in simulators and devices. Thanks!
